#!/bin/bash

# general alt:V server options
ALTV_SERVER_NAME:-"Alt:V Server on Docker!"
ALTV_SERVER_HOST:-"0.0.0.0"
ALTV_SERVER_PORT:-"7788"
ALTV_SERVER_PLAYERS:-"10"
ALTV_SERVER_PASSWORD:-""
ALTV_SERVER_ANNOUNCE:-"false"
ALTV_SERVER_TOKEN:-""
ALTV_SERVER_GAMEMODE:-"none"
ALTV_SERVER_WEBSITE:-""
ALTV_SERVER_LANGUAGE:-"en"
ALTV_SERVER_DESCRIPTION:-"A Alt:V server running in a Docker container."
ALTV_SERVER_MODULES:-"csharp-module,js-module"
ALTV_SERVER_RESOURCES:-""
ALTV_SERVER_LOG_PATH:-""
ALTV_SERVER_EXTRA_RES_PATH:-""
ALTV_SERVER_NO_LOGFILE:-"true"
ALTV_SERVER_JUSTPACK:-""
ALTV_SERVER_DEBUG:-"false"
ALTV_SERVER_EARLYAUTH_URL:-""

#alt:V discord auth options

ALTV_AUTH_ENABLE_WHITELIST:-"false"
ALTV_AUTH_CLIENT_ID:-"<client_id>"
ALTV_AUTH_CLIENT_SECRET:-"<client_secret>"
ALTV_AUTH_BOT_SECRET:-""
ALTV_AUTH_SERVER_ID:-""
ALTV_AUTH_ROLE_WHITELIST_ID:-""
ALTV_AUTH_REDIRECT_IP:-"127.0.0.1"

# alt:V server CDN options
ALTV_SERVER_CDN_URL=${ALTV_SERVER_CDN_URL:-""}

if [ ! -z "$ALTV_SERVER_PASSWORD" ]; then
    ALTV_SERVER_PASSWORD="password: $ALTV_SERVER_PASSWORD"
fi

if [ ! -z "$ALTV_SERVER_TOKEN" ]; then
    ALTV_SERVER_TOKEN="token: $ALTV_SERVER_TOKEN"
fi

if [ ! -z "$ALTV_SERVER_WEBSITE" ]; then
    ALTV_SERVER_WEBSITE="website: $ALTV_SERVER_WEBSITE"
fi

if [ ! -z "$ALTV_SERVER_LOG_PATH" ]; then
    ALTV_SERVER_LOG_PATH="--logfile $ALTV_SERVER_LOG_PATH"
fi

if [ ! -z "$ALTV_SERVER_EXTRA_RES_PATH" ]; then
    ALTV_SERVER_EXTRA_RES_PATH="--extra-res-folder $ALTV_SERVER_EXTRA_RES_PATH"
fi

if [ "$ALTV_SERVER_NO_LOGFILE" = "true" ]; then
    ALTV_SERVER_NO_LOGFILE="--no-logfile"
else
    ALTV_SERVER_NO_LOGFILE=""
fi

if [ "$ALTV_SERVER_JUSTPACK" = "true" ]; then
    ALTV_SERVER_JUSTPACK="--justpack"
fi

if [ ! -z "$ALTV_SERVER_CDN_URL" ]; then
    ALTV_SERVER_CDN_URL="useCdn: true
cdnUrl: \"$ALTV_SERVER_CDN_URL\""
fi

cat <<EOF >/opt/altv/AltV.Net.Host.runtimeconfig.json
{
  "runtimeOptions": {
    "tfm": "net6",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.0"
    }
  }
}
EOF

cat <<EOF >/opt/altv/server.cfg
name: "$ALTV_SERVER_NAME"
host: "$ALTV_SERVER_HOST"
port: $ALTV_SERVER_PORT
debug: $ALTV_SERVER_DEBUG
players: $ALTV_SERVER_PLAYERS
announce: $ALTV_SERVER_ANNOUNCE
gamemode: "$ALTV_SERVER_GAMEMODE"
language: "$ALTV_SERVER_LANGUAGE"
description: "$ALTV_SERVER_DESCRIPTION"
modules: [ $ALTV_SERVER_MODULES ]
resources: [ $ALTV_SERVER_RESOURCES ]

$ALTV_SERVER_EARLYAUTH_URL

$voiceCfg

$ALTV_SERVER_PASSWORD
$ALTV_SERVER_TOKEN
$ALTV_SERVER_WEBSITE
$ALTV_SERVER_CDN_URL
EOF

cat <<EOF >/opt/altv/.env
ENABLE_WHITELIST=$ALTV_AUTH_ENABLE_WHITELIST
CLIENT_ID=$ALTV_AUTH_CLIENT_ID
CLIENT_SECRET=$ALTV_AUTH_CLIENT_SECRET
BOT_SECRET=$ALTV_AUTH_BOT_SECRET
SERVER_ID=$ALTV_AUTH_SERVER_ID
ROLE_WHITELIST_ID=$ALTV_AUTH_ROLE_WHITELIST_ID
REDIRECT_IP=$ALTV_AUTH_REDIRECT_IP
EOF

./altv-server --config=/opt/altv/server.cfg $ALTV_SERVER_LOG_PATH $ALTV_SERVER_NO_LOGFILE $ALTV_SERVER_EXTRA_RES_PATH ${@:1}
